# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
# Format: MAJOR, API, MINOR
mod_version=4.1.18-rc
mc_version=1.20.1
# Dependencies
forge_version=47.4.0
crust_api_version=7230959
crust_src_version=7230962
jei_version=7253590
jade_version=6855440
tc_version=6777068
mantle_version=6819217