# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
#
# Format: MAJOR, API, MINOR
mod_version=4.1.25
#
# MC
mc_version=1.20.1
#
# Forge
forge_version=47.4.10
#
# crust-1.20.1-5.0.0
crust_api_version=8728172
crust_src_version=8728173
#
# JEI
jei_version=7253590
#
# Jade
jade_version=6855440
#
# Tinkers Construct
tc_version=7449219
mantle_version=7563777
#
# Ryoamic Lights
ryoamic_version=5353333
ryoamic_src_version=5353334
obsidianui_version=5279713
# HarvestCraft
hvcraft_cr_version=4687624
hvcraft_fc_version=5097798
#
# Mixin Extras
# mixinextras_version=0.5.3